[font]
  size=10
  normal={ family = "JetBrainsMono Nerd Font Mono", style = "Regular" }

[window]
  #title="3drenv"
  opacity=0.9
#startup_mode = "Maximized"
  dimensions = { columns = 200, lines = 60 }

[selection]
  save_to_clipboard = true

[terminal]

[terminal.shell]
  program = "zellij"
  args = [ "-l", "welcome", ]
#  args = [ "attach", "-c", "FatNFurious", ]
#  program = "ssh"
#  args = [ "instalador@192.168.122.25", "-t", ".local/bin/zellij", "attach", "-c", "Virtual", ]

